version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    container_name: frontend

    working_dir: /app

    ports:
      - "3000:3000"
      - "9229:9229"

    command: npm run dev

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      # Next.js hot reload settings
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

      # Debug settings
      DEBUG: "*"
      NEXTAUTH_DEBUG: "true"

      # API configuration
      # Browser side calls
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:8080/api"

      # Next.js server-side calls (Docker to Docker)
      API_BASE_URL: "http://app:8080/api"

      # NextAuth
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "12D16C923BA17672F89B18C1DB22A"

      NODE_ENV: "development"

    networks:
      - mynetwork


networks:
  mynetwork:
    external: true